# Generated by Django 5.2.2 on 2025-06-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = []
