# Generated by Django 5.2.2 on 2025-07-03 13:38

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    default_categories = [
        ("Electronics", "electronics"),
        ("Clothing", "clothing"),
        ("Home & Garden", "home-garden"),
        ("Beauty & Personal Care", "beauty"),
        ("Sports & Outdoors", "sports"),
        ("Toys & Games", "toys"),
        ("Food & Beverage", "food"),
        ("Books & Media", "books"),
        ("Office Supplies", "office"),
        ("Health & Wellness", "health"),
        ("Automotive", "automotive"),
        ("Pet Supplies", "pets"),
        ("Household Goods", "household"),
        ("Jewelry & Accessories", "jewelry"),
        ("Arts & Crafts", "arts"),
        ("Other", "other")
    ]
    
    for title, slug in default_categories:
        Category.objects.get_or_create(title=title, slug=slug)

class Migration(migrations.Migration):

    dependencies = [
        # Add your last core migration here
        ('core', '0004_alter_profile_id_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]