# Generated by Django 5.2.2 on 2025-08-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_load_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product_price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product_title",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_sku",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
