# Generated by Django 5.2.2 on 2025-10-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_order_product_remove_order_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="number",
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
