# Generated by Django 5.2.2 on 2025-12-27 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_orderitem_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="number",
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_sku",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("owner", "sku")},
        ),
        migrations.AlterModelTable(
            name="profile",
            table=None,
        ),
    ]
