# Generated by Django 5.2.2 on 2026-02-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_feature_plan_profile_country_profile_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="ai_request_limit",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="subscription",
            name="ai_requests_used",
            field=models.IntegerField(default=0),
        ),
    ]
